// pages/c/[slug].vue
<template>
  <div class="min-h-screen bg-gray-50">
    <div v-if="pending" class="flex items-center justify-center min-h-screen">
      <UIcon name="i-heroicons-arrow-path" class="w-8 h-8 animate-spin" />
    </div>
    
    <div v-else-if="error" class="flex items-center justify-center min-h-screen">
      <div class="text-center">
        <h1 class="text-2xl font-bold text-gray-900 mb-2">Campaign Not Found</h1>
        <p class="text-gray-600 mb-4">The campaign you're looking for doesn't exist or has been removed.</p>
        <UButton to="/">Go Home</UButton>
      </div>
    </div>
    
    <div v-else class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Header -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">
          {{ campaign.name }}
        </h1>
        <p v-if="campaign.description" class="text-lg text-gray-600 mb-4">
          {{ campaign.description }}
        </p>
        <p class="text-sm text-gray-500">
          Upload your photo and create a personalized image with this frame
        </p>
      </div>
      
      <div class="grid lg:grid-cols-2 gap-8">
        <!-- Upload & Controls -->
        <div class="space-y-6">
          <UCard class="p-6">
            <h3 class="text-lg font-semibold mb-4">Upload Your Photo</h3>
            
            <div 
              class="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-gray-400 transition-colors"
              :class="{ 'border-blue-500 bg-blue-50': isDragging }"
              @drop="handleDrop"
              @dragover.prevent="isDragging = true"
              @dragleave="isDragging = false"
            >
              <input
                ref="fileInput"
                type="file"
                accept="image/*"
                class="hidden"
                @change="handleFileSelect"
              />
              
              <div v-if="!userImageFile">
                <Icon name="i-heroicons-cloud-arrow-up" class="w-12 h-12 text-gray-400 mx-auto mb-4" />
                <p class="text-lg font-medium text-gray-900 mb-2">
                  Choose Your Photo
                </p>
                <p class="text-gray-600 mb-4">
                  Drag and drop or click to browse
                </p>
                <UButton @click="$refs.fileInput.click()" variant="outline">
                  Select Photo
                </UButton>
              </div>
              
              <div v-else class="space-y-4">
                <p class="text-green-600 font-medium">
                  ✓ Photo uploaded: {{ userImageFile.name }}
                </p>
                <UButton @click="$refs.fileInput.click()" variant="outline" size="sm">
                  Change Photo
                </UButton>
              </div>
            </div>
          </UCard>
          
          <!-- Controls -->
          <UCard v-if="userImageFile" class="p-6">
            <h3 class="text-lg font-semibold mb-4">Adjust Your Photo</h3>
            
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                  Zoom: {{ Math.round(composer.state.scale * 100) }}%
                </label>
                <URange 
                  v-model="zoomValue"
                  :min="10"
                  :max="300"
                  :step="5"
                  @input="handleZoomChange"
                />
              </div>
              
              <div class="flex space-x-2">
                <UButton @click="resetImage" variant="outline" size="sm" class="flex-1">
                  Reset
                </UButton>
                <UButton @click="downloadPng" size="sm" class="flex-1">
                  Download PNG
                </UButton>
                <UButton @click="downloadJpeg" variant="outline" size="sm" class="flex-1">
                  Download JPEG
                </UButton>
              </div>
            </div>
          </UCard>
        </div>
        
        <!-- Preview -->
        <div>
          <UCard class="p-6">
            <h3 class="text-lg font-semibold mb-4">Preview</h3>
            
            <div class="relative">
              <canvas
                ref="canvasRef"
                class="w-full border rounded-lg shadow-sm cursor-move"
                :class="{ 'cursor-grabbing': isDragging }"
                @mousedown="startDrag"
                @mousemove="drag"
                @mouseup="endDrag"
                @mouseleave="endDrag"
                @touchstart="startDrag"
                @touchmove="drag"
                @touchend="endDrag"
              />
              
              <div v-if="!userImageFile" class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 rounded-lg">
                <p class="text-white text-lg font-medium">
                  Upload a photo to see preview
                </p>
              </div>
            </div>
          </UCard>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const route = useRoute()
const { getPublicCampaign, recordMetric } = useApi()
const composer = useCanvasComposer()

const slug = String(route.params.slug);

// Fetch campaign data
const { data: campaign, pending, error } = await useLazyAsyncData(
  `campaign-${slug}`,
  () => getPublicCampaign(slug)
)

// Record visit metric
if (campaign.value && !error.value) {
  recordMetric(slug, 'visit').catch(() => {})
}

// Reactive state
const isDragging = ref(false)
const userImageFile = ref(null)
const canvasRef = ref()
const zoomValue = ref(100)

// Drag state
const dragState = reactive({
  isDragging: false,
  startX: 0,
  startY: 0,
  startOffsetX: 0,
  startOffsetY: 0
})

// Initialize canvas when component mounts
onMounted(async () => {
  if (canvasRef.value && campaign.value) {
    const aspectParts = campaign.value.aspectRatio.split(':')
    const aspectRatio = parseInt(aspectParts[0]) / parseInt(aspectParts[1])
    
    let canvasWidth = 600
    let canvasHeight = canvasWidth / aspectRatio
    
    // Adjust for mobile
    if (window.innerWidth < 768) {
      canvasWidth = Math.min(400, window.innerWidth - 64)
      canvasHeight = canvasWidth / aspectRatio
    }
    
    composer.initCanvas(canvasRef.value, canvasWidth, canvasHeight)
    await composer.loadFrameImage(campaign.value.frameAsset.url)
    composer.render()
  }
})

const handleFileSelect = async (event) => {
  const target = event.target
  const file = target.files?.[0]
  if (file) {
    await processFile(file)
  }
}

const handleDrop = async (event) => {
  event.preventDefault()
  isDragging.value = false
  
  const file = event.dataTransfer?.files[0]
  if (file) {
    await processFile(file)
  }
}

const processFile = async (file) => {
  try {
    userImageFile.value = file
    await composer.loadUserImage(file)
    zoomValue.value = Math.round(composer.state.scale * 100)
    
    // Record render metric
    if (campaign.value) {
      recordMetric(slug, 'render').catch(() => {})
    }
  } catch (error) {
    console.error('Error processing file:', error)
  }
}

const handleZoomChange = (value) => {
  composer.setScale(value / 100)
}

const resetImage = () => {
  composer.resetTransform()
  zoomValue.value = Math.round(composer.state.scale * 100)
}

const downloadPng = () => {
  if (campaign.value) {
    composer.downloadImage(`${campaign.value.name}-frame.png`, 'png')
    recordMetric(slug, 'download').catch(() => {})
  }
}

const downloadJpeg = () => {
  if (campaign.value) {
    composer.downloadImage(`${campaign.value.name}-frame.jpg`, 'jpeg')
    recordMetric(slug, 'download').catch(() => {})
  }
}

// Drag functionality
const getEventPos = (event) => {
  if ('touches' in event) {
    return { x: event.touches[0].clientX, y: event.touches[0].clientY }
  }
  return { x: event.clientX, y: event.clientY }
}

const startDrag = (event) => {
  if (!userImageFile.value) return
  
  event.preventDefault()
  const pos = getEventPos(event)
  
  dragState.isDragging = true
  dragState.startX = pos.x
  dragState.startY = pos.y
  dragState.startOffsetX = composer.state.offsetX
  dragState.startOffsetY = composer.state.offsetY
}

const drag = (event) => {
  if (!dragState.isDragging || !userImageFile.value) return
  
  event.preventDefault()
  const pos = getEventPos(event)
  
  const deltaX = pos.x - dragState.startX
  const deltaY = pos.y - dragState.startY
  
  composer.setOffset(
    dragState.startOffsetX + deltaX,
    dragState.startOffsetY + deltaY
  )
}

const endDrag = () => {
  dragState.isDragging = false
}

// SEO
useSeoMeta({
  title: computed(() => campaign.value ? `${campaign.value.name} - Phrames` : 'Campaign - Phrames'),
  description: computed(() => campaign.value?.description || 'Create a personalized image with this photo frame'),
  ogTitle: computed(() => campaign.value?.name),
  ogDescription: computed(() => campaign.value?.description || 'Create a personalized image with this photo frame'),
  ogImage: computed(() => campaign.value?.frameAsset.url)
})
</script>

// next-app/app/c/[slug]/page.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { DownloadIcon, ShareIcon, PhotoIcon } from '@heroicons/react/24/outline'

interface Campaign {
  id: string
  name: string
  slug: string
  description: string
  frameAsset: {
    url: string
    width: number
    height: number
  }
}

export default function PublicCampaignPage({ params }: { params: { slug: string } }) {
  const [campaign, setCampaign] = useState<Campaign | null>(null)
  const [userImage, setUserImage] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [processing, setProcessing] = useState(false)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    // Fetch campaign data
    fetchCampaign()
  }, [params.slug])

  const fetchCampaign = async () => {
    try {
      const response = await fetch(`/api/public/campaigns/${params.slug}`)
      if (response.ok) {
        const data = await response.json()
        setCampaign(data)
      }
    } catch (error) {
      console.error('Failed to fetch campaign:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = (e) => {
        setUserImage(e.target?.result as string)
      }
      reader.readAsDataURL(file)
    }
  }

  const generateFramedImage = () => {
    if (!campaign || !userImage || !canvasRef.current) return

    setProcessing(true)
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    // Set canvas size
    canvas.width = campaign.frameAsset.width
    canvas.height = campaign.frameAsset.height

    const userImg = new Image()
    const frameImg = new Image()

    userImg.onload = () => {
      frameImg.onload = () => {
        // Draw user image (background)
        ctx.drawImage(userImg, 0, 0, canvas.width, canvas.height)
        
        // Draw frame (overlay)
        ctx.drawImage(frameImg, 0, 0, canvas.width, canvas.height)
        
        setProcessing(false)
      }
      frameImg.src = campaign.frameAsset.url
    }
    userImg.src = userImage
  }

  const downloadImage = () => {
    if (!canvasRef.current) return
    
    const link = document.createElement('a')
    link.download = `${campaign?.name || 'framed-image'}.png`
    link.href = canvasRef.current.toDataURL()
    link.click()
  }

  const shareImage = async () => {
    if (!canvasRef.current) return

    try {
      const canvas = canvasRef.current
      canvas.toBlob(async (blob) => {
        if (blob && navigator.share) {
          const file = new File([blob], `${campaign?.name || 'framed-image'}.png`, { type: 'image/png' })
          await navigator.share({
            title: campaign?.name,
            text: campaign?.description,
            files: [file]
          })
        }
      })
    } catch (error) {
      console.error('Sharing failed:', error)
    }
  }

  useEffect(() => {
    if (userImage && campaign) {
      generateFramedImage()
    }
  }, [userImage, campaign])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-25">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#00dd78] mx-auto mb-4"></div>
          <p className="text-sm text-gray-600">Loading campaign...</p>
        </div>
      </div>
    )
  }

  if (!campaign) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-25">
        <Card className="max-w-md mx-auto">
          <CardContent className="text-center py-16">
            <h1 className="text-2xl font-bold text-gray-900 mb-4">Campaign Not Found</h1>
            <p className="text-gray-600 mb-6">
              The campaign you're looking for doesn't exist or has been removed.
            </p>
            <Button asChild>
              <a href="/">Go Home</a>
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-25">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <div className="w-6 h-6 bg-[#00dd78] rounded mr-2"></div>
              <span className="text-xl font-bold text-[#002400]">phrames</span>
            </div>
            <Button variant="secondary" asChild>
              <a href="/">Create Your Own</a>
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-[#002400] mb-4">{campaign.name}</h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            {campaign.description}
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Upload Section */}
          <Card>
            <CardContent className="p-8">
              <h2 className="text-xl font-semibold text-[#002400] mb-6">Upload Your Photo</h2>
              
              {!userImage ? (
                <div 
                  className="border-2 border-dashed border-gray-300 rounded-lg p-12 text-center cursor-pointer hover:border-[#00dd78] transition-colors"
                  onClick={() => fileInputRef.current?.click()}
                >
                  <PhotoIcon className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                  <p className="text-gray-600 mb-2">Click to upload your photo</p>
                  <p className="text-sm text-gray-500">PNG, JPG up to 10MB</p>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="relative">
                    <img 
                      src={userImage} 
                      alt="Your uploaded photo" 
                      className="w-full h-64 object-cover rounded-lg"
                    />
                  </div>
                  <Button 
                    variant="secondary" 
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full"
                  >
                    Change Photo
                  </Button>
                </div>
              )}

              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleImageUpload}
                className="hidden"
              />
            </CardContent>
          </Card>

          {/* Preview Section */}
          <Card>
            <CardContent className="p-8">
              <h2 className="text-xl font-semibold text-[#002400] mb-6">Your Framed Photo</h2>
              
              {userImage ? (
                <div className="space-y-4">
                  <div className="relative bg-gray-100 rounded-lg overflow-hidden">
                    <canvas
                      ref={canvasRef}
                      className="w-full h-auto max-h-96 object-contain"
                      style={{ display: processing ? 'none' : 'block' }}
                    />
                    {processing && (
                      <div className="flex items-center justify-center h-64">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#00dd78]"></div>
                      </div>
                    )}
                  </div>
                  
                  <div className="flex gap-3">
                    <Button 
                      onClick={downloadImage}
                      className="flex-1 bg-[#00dd78] text-[#002400] hover:bg-[#00dd78]/90"
                      disabled={processing}
                    >
                      <DownloadIcon className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                    <Button 
                      onClick={shareImage}
                      variant="secondary"
                      disabled={processing}
                    >
                      <ShareIcon className="w-4 h-4 mr-2" />
                      Share
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-center h-64 bg-gray-100 rounded-lg">
                  <div className="text-center">
                    <PhotoIcon className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                    <p className="text-gray-500">Upload a photo to see your framed image</p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Instructions */}
        <Card className="mt-8">
          <CardContent className="p-8">
            <h3 className="text-lg font-semibold text-[#002400] mb-4">How to use:</h3>
            <div className="grid md:grid-cols-3 gap-6 text-sm text-gray-600">
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#00dd78] text-white rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">1</div>
                <p>Upload your photo using the upload area on the left</p>
              </div>
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#00dd78] text-white rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">2</div>
                <p>Your photo will automatically be framed with the campaign design</p>
              </div>
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#00dd78] text-white rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">3</div>
                <p>Download or share your framed photo on social media</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-gray-200 mt-16">
        <div className="max-w-4xl mx-auto px-4 py-8 text-center">
          <div className="flex items-center justify-center mb-4">
            <div className="w-6 h-6 bg-[#00dd78] rounded mr-2"></div>
            <span className="text-lg font-bold text-[#002400]">phrames</span>
          </div>
          <p className="text-sm text-gray-600">
            Create your own frame campaign at{' '}
            <a href="/" className="text-[#00dd78] hover:underline">
              phrames.cleffon.com
            </a>
          </p>
        </div>
      </footer>
    </div>
  )
}
