// pages/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div class="text-center">
        <h2 class="text-3xl font-bold text-gray-900">
          Sign in to Phrames
        </h2>
        <p class="mt-2 text-gray-600">
          Welcome back! Please sign in to your account.
        </p>
      </div>
      
      <UCard class="p-6">
        <UForm 
          :schema="loginSchema" 
          :state="form" 
          @submit="handleLogin"
          class="space-y-4"
        >
          <UFormGroup label="Email" name="email">
            <UInput 
              v-model="form.email" 
              type="email" 
              placeholder="Enter your email"
              :disabled="loading"
            />
          </UFormGroup>
          
          <UFormGroup label="Password" name="password">
            <UInput 
              v-model="form.password" 
              type="password" 
              placeholder="Enter your password"
              :disabled="loading"
            />
          </UFormGroup>
          
          <UButton 
            type="submit" 
            block 
            :loading="loading"
            :disabled="loading"
          >
            Sign In
          </UButton>
        </UForm>
        
        <div class="mt-6 text-center">
          <p class="text-sm text-gray-600">
            Don't have an account?
            <NuxtLink to="/signup" class="text-blue-600 hover:text-blue-500">
              Sign up here
            </NuxtLink>
          </p>
        </div>
      </UCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { z } from 'zod'

const { login, loading, initAuth } = useAuth()
const toast = useToast()

// Initialize Firebase auth
onMounted(() => {
  initAuth()
})

const loginSchema = z.object({
  email: z.string().email('Invalid email'),
  password: z.string().min(1, 'Password is required')
})

const form = reactive({
  email: '',
  password: ''
})

const handleLogin = async () => {
  try {
    await login(form.email, form.password)
    toast.add({
      title: 'Success',
      description: 'Welcome back!',
      color: 'green'
    })
  } catch (error) {
    toast.add({
      title: 'Error',
      description: error.message,
      color: 'red'
    })
  }
}

useSeoMeta({
  title: 'Sign In - Phrames',
  description: 'Sign in to your Phrames account to manage your photo frame campaigns.'
})
</script>

// next-app/app/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from '@/components/ui/toaster'

export default function LoginPage() {
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  })
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    
    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      })

      if (response.ok) {
        toast('Successfully signed in!', 'success')
        router.push('/dashboard')
      } else {
        const error = await response.json()
        toast(error.message || 'Login failed', 'error')
      }
    } catch (error) {
      console.error('Login error:', error)
      toast('Something went wrong. Please try again.', 'error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col justify-center bg-gray-25 py-12 sm:px-6 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-md">
        <Link href="/" className="flex justify-center">
          <div className="flex items-center">
            <div className="w-8 h-8 bg-[#00dd78] rounded mr-2"></div>
            <span className="text-2xl font-bold text-[#002400]">phrames</span>
          </div>
        </Link>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="text-2xl">Welcome back</CardTitle>
            <CardDescription>
              Sign in to your account to continue creating amazing frame campaigns
            </CardDescription>
          </CardHeader>
          
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <Label htmlFor="email">Email address</Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                  placeholder="Enter your email"
                  required
                />
              </div>

              <div>
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  value={formData.password}
                  onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
                  placeholder="Enter your password"
                  required
                />
              </div>

              <Button
                type="submit"
                disabled={loading}
                className="w-full bg-[#00dd78] text-[#002400] hover:bg-[#00dd78]/90"
              >
                {loading ? 'Signing in...' : 'Sign in'}
              </Button>
            </form>

            <div className="mt-6 text-center">
              <span className="text-sm text-gray-600">
                Don't have an account?{' '}
              </span>
              <Link href="/signup" className="font-medium text-[#00dd78] hover:text-[#00dd78]/80">
                Sign up
              </Link>
            </div>
          </CardContent>
        </Card>

        <div className="mt-8 text-center">
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-700">
            ← Back to homepage
          </Link>
        </div>
      </div>
    </div>
  )
}
