// components/ui/Button.vue
<template>
  <component
    :is="tag"
    :class="buttonClasses"
    :disabled="disabled || loading"
    v-bind="$attrs"
  >
    <div v-if="loading" class="animate-spin -ml-1 mr-2 h-4 w-4">
      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
    </div>
    <slot />
  </component>
</template>

<script setup lang="ts">
interface Props {
  variant?: 'primary' | 'secondary' | 'tertiary' | 'destructive' | 'ghost'
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  disabled?: boolean
  loading?: boolean
  tag?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  loading: false,
  tag: 'button'
})

const buttonClasses = computed(() => {
  const base = 'inline-flex items-center justify-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
  
  const variants = {
    primary: 'bg-primary-600 text-white shadow-sm hover:bg-primary-700 focus-visible:ring-primary-500',
    secondary: 'bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-gray-500',
    tertiary: 'text-primary-700 hover:text-primary-800 hover:bg-primary-50 focus-visible:ring-primary-500',
    destructive: 'bg-error-600 text-white shadow-sm hover:bg-error-700 focus-visible:ring-error-500',
    ghost: 'text-gray-700 hover:text-gray-900 hover:bg-gray-100 focus-visible:ring-gray-500'
  }
  
  const sizes = {
    xs: 'h-8 px-3 text-xs rounded-lg',
    sm: 'h-9 px-3 text-sm rounded-lg',
    md: 'h-10 px-4 text-sm rounded-lg',
    lg: 'h-11 px-6 text-base rounded-xl',
    xl: 'h-12 px-7 text-base rounded-xl'
  }
  
  return [base, variants[props.variant], sizes[props.size]].join(' ')
})
</script>

// next-app/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-lg text-sm font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-600 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 untitled-ui-shadow-xs",
  {
    variants: {
      variant: {
        primary: "bg-primary-600 text-white hover:bg-primary-700 focus:bg-primary-700 active:bg-primary-800",
        secondary: "bg-white text-gray-700 border border-gray-300 hover:bg-gray-50 focus:bg-gray-50 active:bg-gray-100",
        "secondary-gray": "bg-white text-gray-700 border border-gray-300 hover:bg-gray-50 focus:bg-gray-50",
        tertiary: "bg-transparent text-gray-600 hover:bg-gray-50 focus:bg-gray-50 active:bg-gray-100",
        "tertiary-gray": "bg-transparent text-gray-500 hover:text-gray-600 hover:bg-gray-50 focus:bg-gray-50",
        "link-color": "bg-transparent text-primary-700 hover:text-primary-800 p-0 h-auto font-semibold",
        "link-gray": "bg-transparent text-gray-500 hover:text-gray-600 p-0 h-auto font-medium",
        destructive: "bg-red-600 text-white hover:bg-red-700 focus:bg-red-700 active:bg-red-800",
        "destructive-secondary": "bg-white text-red-700 border border-red-300 hover:bg-red-50 focus:bg-red-50",
      },
      size: {
        sm: "h-9 px-3.5 py-2 text-sm",
        md: "h-10 px-4 py-2.5 text-sm",
        lg: "h-11 px-4.5 py-2.5 text-base",
        xl: "h-12 px-5 py-3 text-base",
        "2xl": "h-15 px-7 py-4 text-lg",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "md",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
