// next-app/app/dashboard/page.tsx
'use client'

import { useAuth } from '@/lib/auth-context'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuLabel, 
  DropdownMenuSeparator, 
  DropdownMenuTrigger 
} from '@/components/ui/dropdown-menu'
import { PlusIcon, PhotoIcon, EyeIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline'

export default function DashboardPage() {
  const { user, loading, logout } = useAuth()
  const router = useRouter()

  useEffect(() => {
    if (!loading && !user) {
      router.push('/login')
    }
  }, [user, loading, router])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-25">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600 mx-auto mb-4"></div>
          <p className="text-sm text-gray-600">Loading your dashboard...</p>
        </div>
      </div>
    )
  }

  if (!user) {
    return null
  }

  const handleLogout = async () => {
    try {
      await logout()
      router.push('/')
    } catch (error) {
      console.error('Logout failed:', error)
    }
  }

  const getUserInitials = (email: string) => {
    return email.split('@')[0].slice(0, 2).toUpperCase()
  }

  return (
    <div className="min-h-screen bg-gray-25">
      {/* Navigation */}
      <nav className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 justify-between items-center">
            <div className="flex items-center">
              <h1 className="text-xl font-bold text-gray-900">Phrames</h1>
            </div>
            <div className="flex items-center gap-4">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="tertiary" className="relative h-8 w-8 rounded-full">
                    <Avatar className="h-8 w-8">
                      <AvatarImage src={user.photoURL || ''} alt={user.email || ''} />
                      <AvatarFallback className="text-xs">
                        {getUserInitials(user.email || 'U')}
                      </AvatarFallback>
                    </Avatar>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-56" align="end" forceMount>
                  <DropdownMenuLabel className="font-normal">
                    <div className="flex flex-col space-y-1">
                      <p className="text-sm font-medium leading-none">Account</p>
                      <p className="text-xs leading-none text-gray-600">
                        {user.email}
                      </p>
                    </div>
                  </DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={handleLogout}>
                    Sign out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
          <p className="mt-2 text-gray-600">
            Manage your frame campaigns and track their performance
          </p>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Total Campaigns
              </CardTitle>
              <PhotoIcon className="h-4 w-4 text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">0</div>
              <p className="text-xs text-gray-600">
                +0 from last month
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Total Views
              </CardTitle>
              <EyeIcon className="h-4 w-4 text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">0</div>
              <p className="text-xs text-gray-600">
                +0 from last month
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Downloads
              </CardTitle>
              <ArrowDownTrayIcon className="h-4 w-4 text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">0</div>
              <p className="text-xs text-gray-600">
                +0 from last month
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Active Campaigns
              </CardTitle>
              <div className="h-2 w-2 bg-green-500 rounded-full" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">0</div>
              <p className="text-xs text-gray-600">
                Currently active
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Empty State */}
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-6">
              <PhotoIcon className="w-8 h-8 text-gray-400" />
            </div>
            <CardTitle className="text-xl mb-2">No campaigns yet</CardTitle>
            <CardDescription className="text-center mb-6 max-w-sm">
              Get started by creating your first frame campaign. Upload your design and start sharing!
            </CardDescription>
            <Button size="lg" className="flex items-center gap-2" onClick={() => router.push('/create')}>
              <PlusIcon className="w-4 h-4" />
              Create your first campaign
            </Button>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}

// pages/dashboard/index.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <div class="bg-white shadow">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-6">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">Dashboard</h1>
            <p class="text-gray-600">Manage your photo frame campaigns</p>
          </div>
          <div class="flex items-center space-x-4">
            <UButton to="/dashboard/campaigns/new" icon="i-heroicons-plus">
              New Campaign
            </UButton>
            <UButton variant="ghost" @click="handleLogout" icon="i-heroicons-arrow-right-on-rectangle">
              Sign Out
            </UButton>
          </div>
        </div>
      </div>
    </div>
    
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div v-if="pending" class="flex justify-center py-12">
        <div class="text-center">
          <UIcon name="i-heroicons-arrow-path" class="w-8 h-8 animate-spin text-blue-600 mx-auto mb-2" />
          <p class="text-gray-600">Loading your campaigns...</p>
        </div>
      </div>
      
      <div v-else-if="error" class="text-center py-12">
        <div class="max-w-md mx-auto">
          <Icon name="i-heroicons-exclamation-triangle" class="w-16 h-16 text-red-400 mx-auto mb-4" />
          <h3 class="text-lg font-medium text-gray-900 mb-2">Failed to load campaigns</h3>
          <p class="text-gray-600 mb-6">
            There was an error loading your campaigns. Please check your connection and try again.
          </p>
          <UButton @click="refresh()" size="lg">Try Again</UButton>
        </div>
      </div>
      
      <div v-else-if="!data?.campaigns?.length" class="text-center py-12">
        <div class="max-w-md mx-auto">
          <Icon name="i-heroicons-photo" class="w-16 h-16 text-gray-400 mx-auto mb-4" />
          <h3 class="text-lg font-medium text-gray-900 mb-2">No campaigns yet</h3>
          <p class="text-gray-600 mb-6">
            Create your first photo frame campaign to get started.
          </p>
          <UButton to="/dashboard/campaigns/new" size="lg">
            Create Your First Campaign
          </UButton>
        </div>
      </div>
      
      <div v-else>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <CampaignCard 
            v-for="campaign in data.campaigns" 
            :key="campaign.id"
            :campaign="campaign"
          />
        </div>
        
        <!-- Pagination -->
        <div v-if="data.pagination.pages > 1" class="mt-8 flex justify-center">
          <UPagination 
            v-model="currentPage"
            :page-count="data.pagination.limit"
            :total="data.pagination.total"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth'
})

const { logout, initAuth } = useAuth()
const { getCampaigns } = useApi()
const toast = useToast()

// Initialize Firebase auth
onMounted(() => {
  initAuth()
})

const currentPage = ref(1)

const { data, pending, error, refresh } = await useLazyAsyncData(
  'campaigns',
  () => getCampaigns(currentPage.value),
  {
    watch: [currentPage]
  }
)

const handleLogout = async () => {
  try {
    await logout()
    await navigateTo('/login')
  } catch (error) {
    toast.add({
      title: 'Error',
      description: 'Failed to sign out',
      color: 'red'
    })
  }
}

useSeoMeta({
  title: 'Dashboard - Phrames',
  description: 'Manage your photo frame campaigns and view analytics.'
})
</script>
