// app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useAuth } from '@/components/AuthProvider'
import AuthGuard from '@/components/AuthGuard'
import CampaignCard from '@/components/CampaignCard'
import ShareModal from '@/components/ShareModal'
import { getUserCampaigns, deleteCampaign, Campaign } from '@/lib/firestore'

// Prevent static generation for this auth-protected page
export const dynamic = 'force-dynamic'
import { toast } from '@/components/ui/toaster'
import { PlusIcon } from '@heroicons/react/24/outline'

export default function DashboardPage() {
  const { user } = useAuth()
  const router = useRouter()
  const [campaigns, setCampaigns] = useState<Campaign[]>([])
  const [loading, setLoading] = useState(true)
  const [deleting, setDeleting] = useState<string | null>(null)
  const [shareModal, setShareModal] = useState<{ isOpen: boolean; campaign: Campaign | null }>({
    isOpen: false,
    campaign: null
  })

  useEffect(() => {
    if (user) {
      loadCampaigns()
    }
  }, [user]) // eslint-disable-line react-hooks/exhaustive-deps

  const loadCampaigns = async () => {
    if (!user) {
      console.log('No user found, skipping campaign load')
      return
    }
    
    console.log('Loading campaigns for user:', user.uid)
    setLoading(true)
    try {
      const userCampaigns = await getUserCampaigns(user.uid)
      console.log('Loaded campaigns:', userCampaigns)
      setCampaigns(userCampaigns)
    } catch (error) {
      console.error('Error loading campaigns:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleEdit = (id: string) => {
    router.push(`/dashboard/campaigns/${id}/edit`)
  }

  const handleShare = (slug: string) => {
    const campaign = campaigns.find(c => c.slug === slug)
    if (campaign) {
      setShareModal({ isOpen: true, campaign })
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this campaign? This action cannot be undone.')) {
      return
    }

    setDeleting(id)
    try {
      const { error } = await deleteCampaign(id)
      if (error) {
        toast('Error deleting campaign: ' + error, 'error')
      } else {
        setCampaigns(campaigns.filter(c => c.id !== id))
        toast('Campaign deleted successfully', 'success')
      }
    } catch (error) {
      console.error('Error deleting campaign:', error)
      toast('Error deleting campaign', 'error')
    } finally {
      setDeleting(null)
    }
  }

  if (loading) {
    return (
      <AuthGuard>
        <div className="min-h-screen flex items-center justify-center">
          <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-secondary"></div>
        </div>
      </AuthGuard>
    )
  }

  return (
    <AuthGuard>
      <div className="min-h-screen bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold text-primary">My Campaigns</h1>
              <p className="text-gray-600 mt-1">
                Manage your frame campaigns and track their performance
              </p>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={loadCampaigns}
                disabled={loading}
                className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-lg font-medium disabled:opacity-50"
              >
                {loading ? 'Loading...' : 'Refresh'}
              </button>
              <Link
                href="/create"
                className="bg-secondary hover:bg-secondary/90 text-primary px-6 py-3 rounded-lg font-semibold flex items-center space-x-2 transition-colors"
              >
                <PlusIcon className="h-5 w-5" />
                <span>Create Campaign</span>
              </Link>
            </div>
          </div>

          {/* Campaigns Grid */}
          {campaigns.length === 0 ? (
            <div className="text-center py-12">
              <div className="mx-auto h-24 w-24 text-gray-400 mb-4">
                <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">No campaigns yet</h3>
              <p className="text-gray-600 mb-6">
                Create your first frame campaign to get started
              </p>
              <Link
                href="/create"
                className="bg-secondary hover:bg-secondary/90 text-primary px-6 py-3 rounded-lg font-semibold inline-flex items-center space-x-2 transition-colors"
              >
                <PlusIcon className="h-5 w-5" />
                <span>Create Your First Campaign</span>
              </Link>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {campaigns.map((campaign) => (
                <div key={campaign.id} className="relative">
                  {deleting === campaign.id && (
                    <div className="absolute inset-0 bg-white bg-opacity-75 flex items-center justify-center z-10 rounded-lg">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-red-500"></div>
                    </div>
                  )}
                  <CampaignCard
                    campaign={campaign}
                    onEdit={handleEdit}
                    onShare={handleShare}
                    onDelete={handleDelete}
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Share Modal */}
        <ShareModal
          isOpen={shareModal.isOpen}
          onClose={() => setShareModal({ isOpen: false, campaign: null })}
          campaignName={shareModal.campaign?.campaignName || ''}
          campaignUrl={shareModal.campaign ? `${window.location.origin}/c/${shareModal.campaign.slug}` : ''}
        />
      </div>
    </AuthGuard>
  )
}

// pages/dashboard/index.vue
<template>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Header -->
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Dashboard</h1>
        <p class="text-gray-600">Manage your photo frame campaigns</p>
      </div>
      <NuxtLink to="/dashboard/campaigns/new">
        <UiButton size="lg">
          <svg class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          Create Campaign
        </UiButton>
      </NuxtLink>
    </div>

    <!-- Loading State -->
    <div v-if="pending" class="flex items-center justify-center py-12">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="text-center py-12">
      <UiCard class="p-8 max-w-md mx-auto">
        <div class="text-error-500 mb-4">
          <svg class="w-12 h-12 mx-auto" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
          </svg>
        </div>
        <h3 class="text-lg font-semibold text-gray-900 mb-2">Unable to load campaigns</h3>
        <p class="text-gray-600 mb-4">{{ error.message || 'Something went wrong' }}</p>
        <UiButton @click="refresh()" variant="secondary">
          Try again
        </UiButton>
      </UiCard>
    </div>

    <!-- Empty State -->
    <div v-else-if="!data?.campaigns?.length" class="text-center py-12">
      <UiCard class="p-12 max-w-lg mx-auto">
        <div class="text-gray-400 mb-6">
          <svg class="w-16 h-16 mx-auto" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Z" />
          </svg>
        </div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">No campaigns yet</h3>
        <p class="text-gray-600 mb-6">
          Create your first photo frame campaign to get started. Upload a PNG frame and share it with your audience.
        </p>
        <NuxtLink to="/dashboard/campaigns/new">
          <UiButton size="lg">
            <svg class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
            Create Your First Campaign
          </UiButton>
        </NuxtLink>
      </UiCard>
    </div>

    <!-- Campaigns Grid -->
    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <CampaignCard
        v-for="campaign in data.campaigns"
        :key="campaign.id"
        :campaign="campaign"
        @deleted="refresh"
      />
    </div>

    <!-- Pagination -->
    <div v-if="data?.pagination && data.pagination.pages > 1" class="mt-8 flex justify-center">
      <nav class="flex items-center space-x-2">
        <UiButton
          v-if="data.pagination.page > 1"
          variant="secondary"
          size="sm"
          @click="goToPage(data.pagination.page - 1)"
        >
          Previous
        </UiButton>
        
        <span class="px-4 py-2 text-sm text-gray-700">
          Page {{ data.pagination.page }} of {{ data.pagination.pages }}
        </span>
        
        <UiButton
          v-if="data.pagination.page < data.pagination.pages"
          variant="secondary"
          size="sm"
          @click="goToPage(data.pagination.page + 1)"
        >
          Next
        </UiButton>
      </nav>
    </div>
  </div>
</template>

<script setup lang="ts">
// Auth protection handled by global middleware

const { getCampaigns } = useApi()

const page = ref(1)
const { data, pending, error, refresh } = await useLazyAsyncData(
  'campaigns',
  () => getCampaigns({ page: page.value }),
  {
    watch: [page]
  }
)

const goToPage = (newPage: number) => {
  page.value = newPage
}

useSeoMeta({
  title: 'Dashboard - Phrames',
  description: 'Manage your photo frame campaigns and view analytics.'
})
</script>
